[package]
name = "fontlugat"
version = "0.0.1"
authors = ["Fatih Gozenc <fatihgozenc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
